### ISSUE TITLE
Possible Bug: Square residuals change colors depending on placement

### ISSUE THREAD

**Issue by bryo5363** [phetsims/least-squares-regression#13]
Test device: MacBook Pro

Operating System: OSX 10.10.1

Browser: Safari 8.0 (10600.1.25.1)

Problem description: When adding more points in the "custom" option, the squared residuals will alternate color depending on placement of the point. 

I am not extremely familiar with least square regression but I believe this might be abnormal behavior

Steps to reproduce:
-open sim
-drag many points on the graph
-access all options (my line, squared residuals for both lines, residuals for both lines, etc)
-when adding points notice that the color of square residuals will change depending on the addition of the new point
Severity:

Screenshots:

![least-square-regression](https://cloud.githubusercontent.com/assets/7717368/6271121/e275edfa-b81b-11e4-807b-e257b2523319.gif)

Troubleshooting information (do not edit):
Name: Least-Squares Regression
URL: http://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.0.0-dev.6/least-squares-regression_en.html
Version: 1.0.0-dev.6
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25
Language: en-us
Window: 1240x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.19)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by amanda-phet** [comment]
I think what is happening here is the red squares are flipping around the residual line. The squares are formed by taking a vertical line from a point to the line (residual) and making a square to the left or right side depending on whether the point is above or below the line. When you move a point, it changes the location of the best-fit line, and hence changes the location of the squares for some points. 

It is difficult to see the best-fit line in your video because it is behind a bunch of squares. Perhaps we should always display the lines on the top-most layer?

**Comment by bryo5363** [comment]
@amanda-phet That's what I was thinking; it gets quite convoluted once many data points are on the graph and becomes nearly impossible to see the best fit lines. Maybe a black outline on each curve would make the lines more apparent?

**Comment by veillette** [comment]
We will have the best fit line and my line on a higher z level (but beneath the data points). This should address a similar concern raised in #8.

**Comment by veillette** [comment]
The best fit line and my line is on top of the residuals.
