### ISSUE TITLE
GraphAxesNode copied from graphing-lines?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#22]
GraphAxesNode looks like a fair amount of the code was copied from graphings-lines.GraphNode. I don't know how much you had to change to make it work for this sim. But do you think it would be feasible (or worth the effort) to generalize graphings-lines.GraphNode, and use in both sims?

**Comment by veillette** [comment]
There is a handful of differences. The major one is the strategy to determine the tick spacing which  is handled dynamically in GraphAxesNodes (based on the range of the graph). Also the position of the axes is different and uses lines instead of arrows. GraphAxesNodes is also responsible for the x and y labels. In addition there is a listener to the grid in GraphAxesNodes.  The origin label ticks is not skipped in GraphAxesNodes but it is in GraphNodes. 

These are all the differences I could find. So it would be possible to generalize it but it would take some amount of work to reconcile the two versions. I'm not certain it is worth it.

**Comment by pixelzoom** [comment]
I'm OK with leaving it as is. I don't have time to reconcile the 2 versions. And rather than reconciling the 2 versions, this basic functionality should be provided by `griddle` (chart repository). So I've created https://github.com/phetsims/griddle/issues/9. 

@bereaphysics please add any other thoughts, then feel free to close this issue.

**Comment by veillette** [comment]
It would be interesting to generate a charting utility that can do the layout but it seems like a lof ot work because there are so many cases/uses to consider. I think this is out of my league.
