### ISSUE TITLE
least-squares-regression fails to build

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/least-squares-regression#42]
```
% grunt
...
Writing HTML
Fatal error: Missing string LEAST_SQUARES_REGRESSION/custom.yAxisTitle in fallback locale (en)
%
```

**Comment by pixelzoom** [comment]
This is similar to https://github.com/phetsims/molecule-shapes/issues/122. I suspect that it's caused by changes made to the string plugin, and that it's not handling the empty string properly.

**Comment by pixelzoom** [comment]
@bereaphysics This is indeed a problem with the build process, and is being worked out in phetsims/molecule-shapes#122.

But as with molecule-shapes, I'm wondering why least-squares-regression has empty strings in its strings file.  Specifically, these entries in least-squares-regression-strings_en.json:

``` js
  "custom.xAxisTitle": {
    "value": ""
  },
  "custom.yAxisTitle": {
    "value": ""
  },
  "custom.reference": {
    "value": ""
  },
  "custom.source": {
    "value": ""
  },
```

Are you allowing translators to set labels for some things that don't have labels in the English version? How are the translators going to know what these keys apply to if they don't see strings in the English version?

**Comment by veillette** [comment]
There are about 50 or so string for least squares regression that have to do with data sets. Custom is a data set with empty strings and it was put in there for consistency with the other data sets. 
 However it is perhaps wiser not to propagate the empty strings all the way to the json file since we probably don't want this to be translated. It is preferable to put the empty strings directly into DataSets.js instead.

**Comment by veillette** [comment]
Oops forgot to tag. https://github.com/phetsims/least-squares-regression/commit/0d7d63703cec8243de3f3a051bb5152c420ce082
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Sounds like the right thing to do. Looks good. Closing.
